BTCUSD_M1_CRYPTO:
  strategy_type: metahar
  symbols: ['BTCUSD', 'ETHUSD', 'XRPUSD', 'LTCUSD', 'ADAUSD']
  predicted_symbol: BTCUSD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_crypto_btcusd_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
ETHUSD_M1_CRYPTO:
  strategy_type: metahar
  symbols: ['BTCUSD', 'ETHUSD', 'XRPUSD', 'LTCUSD', 'ADAUSD']
  predicted_symbol: ETHUSD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_crypto_ethusd_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
XRPUSD_M1_CRYPTO:
  strategy_type: metahar
  symbols: ['BTCUSD', 'ETHUSD', 'XRPUSD', 'LTCUSD', 'ADAUSD']
  predicted_symbol: XRPUSD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_crypto_xrpusd_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
LTCUSD_M1_CRYPTO:
  strategy_type: metahar
  symbols: ['BTCUSD', 'ETHUSD', 'XRPUSD', 'LTCUSD', 'ADAUSD']
  predicted_symbol: LTCUSD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_crypto_ltcusd_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
ADAUSD_M1_CRYPTO:
  strategy_type: metahar
  symbols: ['BTCUSD', 'ETHUSD', 'XRPUSD', 'LTCUSD', 'ADAUSD']
  predicted_symbol: ADAUSD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_crypto_adausd_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
EURUSD_M1_FX:
  strategy_type: metahar
  symbols: ['EURUSD', 'GBPUSD', 'USDJPY', 'USDCHF', 'AUDUSD']
  predicted_symbol: EURUSD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_major_eurusd_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
GBPUSD_M1_FX:
  strategy_type: metahar
  symbols: ['EURUSD', 'GBPUSD', 'USDJPY', 'USDCHF', 'AUDUSD']
  predicted_symbol: GBPUSD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_major_gbpusd_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
USDJPY_M1_FX:
  strategy_type: metahar
  symbols: ['EURUSD', 'GBPUSD', 'USDJPY', 'USDCHF', 'AUDUSD']
  predicted_symbol: USDJPY
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_major_usdjpy_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
USDCHF_M1_FX:
  strategy_type: metahar
  symbols: ['EURUSD', 'GBPUSD', 'USDJPY', 'USDCHF', 'AUDUSD']
  predicted_symbol: USDCHF
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_major_usdchf_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
AUDUSD_M1_FX:
  strategy_type: metahar
  symbols: ['EURUSD', 'GBPUSD', 'USDJPY', 'USDCHF', 'AUDUSD']
  predicted_symbol: AUDUSD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_major_audusd_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
USDCAD_M1_FX:
  strategy_type: metahar
  symbols: ['USDCAD', 'AUDUSD', 'NZDUSD', 'USDHUF', 'USDZAR']
  predicted_symbol: USDCAD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_comm_usdcad_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
AUDUSD_M1_FX:
  strategy_type: metahar
  symbols: ['USDCAD', 'AUDUSD', 'NZDUSD', 'USDHUF', 'USDZAR']
  predicted_symbol: AUDUSD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_comm_audusd_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
NZDUSD_M1_FX:
  strategy_type: metahar
  symbols: ['USDCAD', 'AUDUSD', 'NZDUSD', 'USDHUF', 'USDZAR']
  predicted_symbol: NZDUSD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_comm_nzdusd_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
USDHUF_M1_FX:
  strategy_type: metahar
  symbols: ['USDCAD', 'AUDUSD', 'NZDUSD', 'USDHUF', 'USDZAR']
  predicted_symbol: USDHUF
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_comm_usdhuf_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
USDZAR_M1_FX:
  strategy_type: metahar
  symbols: ['USDCAD', 'AUDUSD', 'NZDUSD', 'USDHUF', 'USDZAR']
  predicted_symbol: USDZAR
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_comm_usdzar_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
US500_cash_M1_IDX:
  strategy_type: metahar
  symbols: ['US500.cash', 'US100.cash', 'GER40.cash', 'UK100.cash', 'FRA40.cash']
  predicted_symbol: US500.cash
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_idx_us500_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
US100_cash_M1_IDX:
  strategy_type: metahar
  symbols: ['US500.cash', 'US100.cash', 'GER40.cash', 'UK100.cash', 'FRA40.cash']
  predicted_symbol: US100.cash
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_idx_US100_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
GER40_cash_M1_IDX:
  strategy_type: metahar
  symbols: ['US500.cash', 'US100.cash', 'GER40.cash', 'UK100.cash', 'FRA40.cash']
  predicted_symbol: GER40.cash
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_idx_ger40_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
UK100_cash_M1_IDX:
  strategy_type: metahar
  symbols: ['US500.cash', 'US100.cash', 'GER40.cash', 'UK100.cash', 'FRA40.cash']
  predicted_symbol: UK100.cash
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_idx_uk100_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
FRA40_cash_M1_IDX:
  strategy_type: metahar
  symbols: ['US500.cash', 'US100.cash', 'GER40.cash', 'UK100.cash', 'FRA40.cash']
  predicted_symbol: FRA40.cash
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_idx_fra40_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
BTCUSD_M1_MIX:
  strategy_type: metahar
  symbols: ['BTCUSD', 'EURUSD', 'XAUUSD', 'US500.cash', 'GBPUSD']
  predicted_symbol: BTCUSD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_mix_btcusd_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
EURUSD_M1_MIX:
  strategy_type: metahar
  symbols: ['BTCUSD', 'EURUSD', 'XAUUSD', 'US500.cash', 'GBPUSD']
  predicted_symbol: EURUSD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_mix_eurusd_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
XAUUSD_M1_MIX:
  strategy_type: metahar
  symbols: ['BTCUSD', 'EURUSD', 'XAUUSD', 'US500.cash', 'GBPUSD']
  predicted_symbol: XAUUSD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_mix_xauusd_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
US500_cash_M1_MIX:
  strategy_type: metahar
  symbols: ['BTCUSD', 'EURUSD', 'XAUUSD', 'US500.cash', 'GBPUSD']
  predicted_symbol: US500.cash
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_mix_us500_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
GBPUSD_M1_MIX:
  strategy_type: metahar
  symbols: ['BTCUSD', 'EURUSD', 'XAUUSD', 'US500.cash', 'GBPUSD']
  predicted_symbol: GBPUSD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_mix_gbpusd_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240