XAUUSD_M1_MIX:
  strategy_type: metahar
  symbols: ['BTCUSD', 'EURUSD', 'XAUUSD', 'US500.cash', 'GBPUSD']
  predicted_symbol: XAUUSD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_mix_xauusd_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
US500_cash_M1_MIX:
  strategy_type: metahar
  symbols: ['BTCUSD', 'EURUSD', 'XAUUSD', 'US500.cash', 'GBPUSD']
  predicted_symbol: US500.cash
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_mix_us500_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240
GBPUSD_M1_MIX:
  strategy_type: metahar
  symbols: ['BTCUSD', 'EURUSD', 'XAUUSD', 'US500.cash', 'GBPUSD']
  predicted_symbol: GBPUSD
  timeframe: mt5.TIMEFRAME_M1
  tag: metahar_mix_gbpusd_m1
  active_hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  short_factor: 15
  long_factor: 240